# Generated by Django 4.0.4 on 2022-04-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronat', '0003_alter_property_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='land',
            name='id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='id',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pronat.property'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pronat.property'),
        ),
        migrations.AlterField(
            model_name='land',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pronat.property'),
        ),
        migrations.AlterField(
            model_name='store',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pronat.property'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pronat.property'),
        ),
    ]
