# Generated by Django 4.0.4 on 2022-04-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronat', '0004_remove_apartment_id_remove_garage_id_remove_land_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
    ]
