# Generated by Django 4.0.4 on 2022-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronat', '0005_remove_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='land',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='slug',
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
