# Generated by Django 4.0.4 on 2022-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronat', '0007_alter_property_description_alter_property_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='floor',
            field=models.IntegerField(default=-1),
        ),
    ]
