# Generated by Django 4.0.4 on 2022-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronat', '0008_alter_store_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='bath_num',
            field=models.IntegerField(),
        ),
    ]
